sudo: required
services:
  - docker

before_install:
  - docker build -t brettc84/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run brettc84/react-test npm test -- --coverage

after_success:
  - docker build -t brettc84/multi-client ./client
  - docker build -t brettc84/multi-nginx ./nginx
  - docker build -t brettc84/multi-worker ./worker
  - docker build -t brettc84/multi-server ./server
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push brettc84/multi-client
  - docker push brettc84/multi-nginx
  - docker push brettc84/multi-worker
  - docker push brettc84/multi-server

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-963455173251"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY